<div class="container">
  <h2 class="text-primary fw-bold"><?= $data['title'] ?></h2>
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 my-5">
    <?php foreach($articles as $article): 
      $desc = $block->parseDescription($article['description']);
    ?>
    <div class="col">
      <div class="card shadow rounded-2">
        <div class="card-img-top">
          <a href="<?= $article['link'] ?>" target="blank">
            <img alt="Thumbnail" src="<?= $desc['img'] ?>">
          </a>
        </div>
        <div class="card-body">
          <a href="<?= $article['link'] ?>" target="blank"><h2 class="fw-bold"><?= $article['title'] ?></h2></a>
          <p class="card-text"><?= $desc['desc'] ?></p>
          <div class="d-flex justify-content-end">
            <small class="text-muted"><?= date('d/m/Y', strtotime($article['pubDate'])) ?></small>
          </div>
        </div>
      </div>
    </div>
    <?php endforeach; ?>
  </div>
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
    <?php for($i=1; $i <= $block->getTotalPages(); $i++): ?>
      <li class="page-item <?= $page == $i ? 'active' : ''?>">
        <a class="page-link" href="<?= "$uri?page=$i" ?>" tabindex="-1" aria-disabled="true"><?= $i ?></a>
      </li>
    <?php endfor; ?>
    </ul>
  </nav>
</div>